#!/usr/bin/env python3
"""
generate_csvw.py - Generate a per-module CSVW group metadata document
(csv-metadata.json) from the shared schema templates in tools/csvw/.

The three schema fragments (vert-schema.json, conversations-schema.json,
participants-schema.json) are the single source of truth for column
definitions, per tools/PIPELINE.md. This script does not encode any schema
knowledge itself — it only assembles them, per module, into one self-contained
CSVW document that lists every <code>.vert.tsv file found in tsv/.

Output: <module>/csv-metadata.json (module root, sibling to tsv/ and metadata/)

Usage:
    python generate_csvw.py <module_dir> [<module_dir> ...]
    python generate_csvw.py --all <KIParla_root>
"""

import argparse
import json
from pathlib import Path

SCHEMA_DIR = Path(__file__).resolve().parent
MODULES = ["KIP", "KIPasti", "ParlaBO", "ParlaTO", "Stra-ParlaBO", "Stra-ParlaTO",
           "KIParla-collection"]


def load_schema(name: str) -> dict:
    schema = json.loads((SCHEMA_DIR / name).read_text(encoding="utf-8"))
    schema.pop("_comment", None)
    return schema


def read_header(path: Path) -> list[str]:
    with path.open(encoding="utf-8") as f:
        return f.readline().rstrip("\r\n").split("\t")


def columns_from_header(header: list[str], known_columns: dict) -> list[dict]:
    """Build a CSVW column list from a real file header, attaching whatever
    column knowledge `known_columns` has for each name. Unmatched columns
    (module-specific extras, or shapes not seen before) pass through with
    just a name/titles pair rather than failing.
    """
    columns = []
    for col in header:
        entry = {"name": col, "titles": col}
        entry.update(known_columns.get(col, {}))
        columns.append(entry)
    return columns


def build_metadata_table_schema(module_dir: Path, filename: str, schema_file: str) -> dict:
    """Build a tableSchema for a metadata/*.tsv file whose column *set* varies
    by module — driven by the file's real header, not an assumed fixed shape.
    """
    known = load_schema(schema_file)
    header = read_header(module_dir / "metadata" / filename)
    return {
        "columns": columns_from_header(header, known["known_columns"]),
        "foreignKeys": known["foreignKeys"],
        "primaryKey": known["primaryKey"],
    }


def build_vert_tables(tsv_dir: Path) -> list[dict]:
    """Build one CSVW table entry per <code>.vert.tsv file.

    Column *sets* are not guaranteed uniform even within one directory (e.g.
    KIParla-collection/tsv mixes a 12- and a 13-column shape, with/without
    `variation`), so files are grouped by their real header. Each distinct
    shape gets one inline tableSchema (tagged with a unique @id); every other
    file with that shape just references it — DRY without assuming
    uniformity.
    """
    known = load_schema("vert-schema.json")
    paths = sorted(p for p in tsv_dir.glob("*.vert.tsv"))
    if not paths:
        raise ValueError(f"No *.vert.tsv files found in {tsv_dir}")

    schema_id_by_shape: dict[tuple, str] = {}
    tables = []
    for path in paths:
        header = tuple(read_header(path))
        code = path.stem.removesuffix(".vert")
        table = {"url": f"tsv/{code}.vert.tsv"}

        if header not in schema_id_by_shape:
            shape_id = f"#vert-schema-{len(schema_id_by_shape) + 1}"
            schema_id_by_shape[header] = shape_id
            table["tableSchema"] = {
                "@id": shape_id,
                "columns": columns_from_header(list(header), known["known_columns"]),
                "foreignKeys": known["foreignKeys"],
                "primaryKey": known["primaryKey"],
            }
        else:
            table["tableSchema"] = {"@id": schema_id_by_shape[header]}

        tables.append(table)

    if len(schema_id_by_shape) > 1:
        print(f"  {tsv_dir}: {len(schema_id_by_shape)} distinct vert.tsv column shapes found")

    return tables


def build_metadata(module_dir: Path) -> dict:
    """Assemble the CSVW group metadata document for one module."""
    conversations_schema = build_metadata_table_schema(
        module_dir, "conversations.tsv", "conversations-schema.json"
    )
    participants_schema = build_metadata_table_schema(
        module_dir, "participants.tsv", "participants-schema.json"
    )

    tables = [
        {"url": "metadata/conversations.tsv", "tableSchema": conversations_schema},
        {"url": "metadata/participants.tsv", "tableSchema": participants_schema},
    ]
    tables.extend(build_vert_tables(module_dir / "tsv"))

    return {
        "@context": "http://www.w3.org/ns/csvw",
        "@id": "csv-metadata.json",
        "dc:description": "Generated by tools/csvw/generate_csvw.py from tools/csvw/*-schema.json — do not hand-edit, regenerate instead.",
        "dialect": {"delimiter": "\t", "header": True, "encoding": "utf-8"},
        "tables": tables,
    }


def generate_for_module(module_dir: Path) -> Path:
    out_path = module_dir / "csv-metadata.json"
    metadata = build_metadata(module_dir)
    out_path.write_text(json.dumps(metadata, indent=2, ensure_ascii=False) + "\n", encoding="utf-8")
    return out_path


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("module_dirs", nargs="*", help="Module directories, e.g. KIP ParlaBO")
    parser.add_argument("--all", metavar="KIPARLA_ROOT",
                         help="Generate for every known module under KIPARLA_ROOT")
    args = parser.parse_args()

    if args.all:
        root = Path(args.all)
        targets = [root / m for m in MODULES if (root / m / "tsv").is_dir()]
    else:
        targets = [Path(d) for d in args.module_dirs]

    if not targets:
        parser.error("Provide module directories, or --all <KIParla_root>")

    for module_dir in targets:
        try:
            out_path = generate_for_module(module_dir)
            print(f"{module_dir}: wrote {out_path}")
        except Exception as exc:
            print(f"{module_dir}: ERROR {exc}")


if __name__ == "__main__":
    main()
